spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///world?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 729186
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 112.124.12.56
    database: 0
    port: 6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl